### ISSUE TITLE
ps2-home validation process

### ISSUE THREAD

**Issue by Jay-Jay-OPL** [suicvne/cue2pops-gui-mac#1]
Hi, 

The admin at ps2-home.com wants to validate you as the developer of this project.  If this is really you, please post here the code that was given to you in order to proceed.

If this isn't you, sorry, there was a member trying to impersonate you at ps2-home.com   You can simply delete this Issue report.

**Comment by suicvne** [comment]
Yes, that is me: code 1239082

**Comment by Jay-Jay-OPL** [comment]
Thanks.  

You can go ahead and delete this Issue.

I will report this to the admin.  He should reply to you soon through the report ticket system. :)
